import { useCallback, useEffect, useState } from 'react';
import { liveQuery } from 'dexie';
import db from '../db/database';
import { useSyncStore } from '../sync/syncStore';
import type { Expense, ExpenseCategory, RecurringExpenseTemplate } from '../types/models';
import { shouldGenerateRecurringExpense } from '../lib/calculations';

export function useExpenses() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const incrementPending = useSyncStore((s) => s.incrementPending);

  // Live query: all expenses, newest first
  useEffect(() => {
    const sub = liveQuery(() =>
      db.expenses.orderBy('date').reverse().toArray()
    ).subscribe({
      next: (data) => { setExpenses(data); setIsLoading(false); },
      error: () => setIsLoading(false),
    });
    return () => sub.unsubscribe();
  }, []);

  // Create an expense
  const addExpense = useCallback(async (data: Omit<Expense, 'id' | 'createdAt' | 'updatedAt' | 'syncedAt'>): Promise<string> => {
    const now = new Date().toISOString();
    const id = await db.expenses.add({ ...data, createdAt: now, updatedAt: now } as Expense);
    incrementPending();
    return String(id);
  }, [incrementPending]);

  // Update an expense
  const updateExpense = useCallback(async (id: string, data: Partial<Expense>) => {
    await db.expenses.update(id, { ...data, updatedAt: new Date().toISOString() });
    incrementPending();
  }, [incrementPending]);

  // Delete an expense
  const deleteExpense = useCallback(async (id: string) => {
    await db.expenses.delete(id);
    incrementPending();
  }, [incrementPending]);

  // Get expenses for a date range
  const getExpensesInRange = useCallback(async (from: string, to: string): Promise<Expense[]> => {
    return db.expenses.where('date').between(from, to, true, true).toArray();
  }, []);

  // Get total by category for a date range
  const getTotalByCategoryInRange = useCallback(async (from: string, to: string): Promise<Record<ExpenseCategory, number>> => {
    const entries = await getExpensesInRange(from, to);
    const totals: Record<string, number> = {};
    for (const e of entries) {
      totals[e.category] = (totals[e.category] || 0) + e.amount;
    }
    return totals as Record<ExpenseCategory, number>;
  }, [getExpensesInRange]);

  // ── Recurring Expense Templates ──

  const [templates, setTemplates] = useState<RecurringExpenseTemplate[]>([]);

  useEffect(() => {
    const sub = liveQuery(() =>
      db.recurringExpenseTemplates.toArray()
    ).subscribe({
      next: (data) => setTemplates(data),
    });
    return () => sub.unsubscribe();
  }, []);

  const addTemplate = useCallback(async (data: Omit<RecurringExpenseTemplate, 'id' | 'createdAt' | 'updatedAt'>): Promise<string> => {
    const now = new Date().toISOString();
    const id = await db.recurringExpenseTemplates.add({ ...data, createdAt: now, updatedAt: now } as RecurringExpenseTemplate);
    return String(id);
  }, []);

  const deleteTemplate = useCallback(async (id: string) => {
    await db.recurringExpenseTemplates.delete(id);
  }, []);

  // Process recurring expenses: check if any templates need new instances
  const processRecurringExpenses = useCallback(async (today: string): Promise<number> => {
    const allTemplates = await db.recurringExpenseTemplates.toArray();
    let generated = 0;

    for (const tmpl of allTemplates) {
      if (shouldGenerateRecurringExpense(tmpl.frequency, tmpl.lastGenerated ?? null, today)) {
        const expense: Omit<Expense, 'id' | 'createdAt' | 'updatedAt' | 'syncedAt'> = {
          date: today,
          category: tmpl.category,
          amount: tmpl.amount,
          description: `${tmpl.description} (auto)`,
          isRecurring: true,
          recurringFrequency: tmpl.frequency,
          isAutoGenerated: true,
          templateId: tmpl.id,
        };
        await addExpense(expense);
        await db.recurringExpenseTemplates.update(tmpl.id!, { lastGenerated: today });
        generated++;
      }
    }
    return generated;
  }, [addExpense]);

  return {
    expenses,
    isLoading,
    addExpense,
    updateExpense,
    deleteExpense,
    getExpensesInRange,
    getTotalByCategoryInRange,
    templates,
    addTemplate,
    deleteTemplate,
    processRecurringExpenses,
  };
}
