// Core data models for QuackManager

export interface EggCollection {
  id?: string;
  date: string; // YYYY-MM-DD
  quantity: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface EggSale {
  id?: string;
  date: string;
  quantity: number;
  pricePerEgg: number;
  total: number;
  customerName?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface IncubationBatch {
  id?: string;
  datePlaced: string;
  quantity: number;
  incubatorId?: string;
  expectedHatchDate: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface DucklingHatch {
  id?: string;
  date: string;
  quantity: number;
  incubationBatchId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface DuckSale {
  id?: string;
  date: string;
  quantity: number;
  priceEach: number;
  total: number;
  customerName?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface FeedPurchase {
  id?: string;
  date: string;
  feedType: string;
  quantity: number;
  unit: 'kg' | 'bag';
  costPerUnit: number;
  totalCost: number;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface FeedUsageLog {
  id?: string;
  date: string;
  quantityKg: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface FeedStock {
  id?: string;
  currentStockKg: number;
  lastUpdated: string;
  dailyAvgConsumptionKg: number;
  lowStockThresholdKg: number;
}

export type ExpenseCategory = 'labor' | 'medicine' | 'transport' | 'electricity' | 'maintenance' | 'other';

export type RecurringFrequency = 'daily' | 'weekly' | 'monthly';

export interface Expense {
  id?: string;
  date: string;
  category: ExpenseCategory;
  amount: number;
  description: string;
  isRecurring?: boolean;
  recurringFrequency?: RecurringFrequency;
  isAutoGenerated?: boolean;
  templateId?: string;
  receiptPhotoUrl?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface RecurringExpenseTemplate {
  id?: string;
  category: ExpenseCategory;
  amount: number;
  description: string;
  frequency: RecurringFrequency;
  lastGenerated?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Customer {
  id?: string;
  name: string;
  phone: string;
  email?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DailyLog {
  id?: string; // YYYY-MM-DD
  date: string;
  eggsCollected: number;
  eggsSold: number;
  ducksSold: number;
  feedUsedKg: number;
  expensesTotal: number;
  revenueTotal: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface FarmSettings {
  id?: string;
  name: string;
  freshnessDays: number;
  lowFeedThresholdDays: number;
  createdAt: string;
  updatedAt: string;
}

export const EXPENSE_CATEGORIES: { value: ExpenseCategory; label: string; icon: string }[] = [
  { value: 'labor', label: 'Labor', icon: 'groups' },
  { value: 'medicine', label: 'Medicine', icon: 'medication' },
  { value: 'transport', label: 'Transport', icon: 'local_shipping' },
  { value: 'electricity', label: 'Electricity', icon: 'bolt' },
  { value: 'maintenance', label: 'Maintenance', icon: 'build' },
  { value: 'other', label: 'Other', icon: 'more_horiz' },
];

export const RECURRING_FREQUENCIES: { value: RecurringFrequency; label: string }[] = [
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
];

// ── Duck Tracking ─────────────────────────────────────────────────────

export type DuckAgeGroup = 'duckling' | 'grower' | 'adult';

export type MortalityCause = 'disease' | 'injury' | 'predator' | 'old_age' | 'unknown';

export interface DuckMortality {
  id?: string;
  date: string;
  quantity: number;
  cause: MortalityCause;
  ageGroup?: DuckAgeGroup;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;
}

export interface DuckInventorySnapshot {
  id?: string;
  date: string;
  totalLive: number;
  ducklings: number;
  growers: number;
  adults: number;
  lastCalculatedAt: string;
}

export const MORTALITY_CAUSES: { value: MortalityCause; label: string; icon: string }[] = [
  { value: 'disease', label: 'Disease', icon: 'sick' },
  { value: 'injury', label: 'Injury', icon: 'bandage' },
  { value: 'predator', label: 'Predator', icon: 'pets' },
  { value: 'old_age', label: 'Old Age', icon: 'cruelty_free' },
  { value: 'unknown', label: 'Unknown', icon: 'help' },
];

export const DUCK_AGE_GROUP_LABELS: Record<DuckAgeGroup, string> = {
  duckling: 'Ducklings (0-2 wks)',
  grower: 'Growers (2-8 wks)',
  adult: 'Adults (8+ wks)',
};
